SRC_FILES=(
    $DIR/_$NAME/src/gatfile.go
    $DIR/_$NAME/src/packets.go
    $DIR/_$NAME/src/botfunc.go
    $DIR/_$NAME/src/botvars.go
    $DIR/_$NAME/src/botloop.go
    $DIR/_$NAME/src/utils.go
    $DIR/_$NAME/src/main.go
)
